import { SiGoogledocs } from "react-icons/si";
import { FaFeatherPointed } from "react-icons/fa6";
import { FaVideo } from "react-icons/fa";

const data = [
  {
    id: 1,
    category: "essays",
    author_name: "David M. Driesen",
    title: "“A World Lost”: Climate, Policy, and Art",
    cover_img: "/images/portal/world_lost_dd.jpg",
    desc: "<i>A World Lost</i> (2013) offers a fascinating and absorbing, albeit deeply troubling, picture of the climate crisis (fig. 1). As an academic lawyer, I tend to focus on actions designed to “mitigate” climate disruption, such as policies to reduce fossil fuel use (which reduce greenhouse gas emissions). At the same time, when I write or teach about ...",
    url: "/works/a-world-lost-climate-policy-art",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl drop-shadow-xl" />
  },
  {
    id: 2,
    category: "essays",
    author_name: "Abby Campanaro",
    title: "Behind the Scenes: Installing “Take Me to the Palace of Love”",
    cover_img: "/images/portal/behind_scenes_ac.jpg",
    desc: "The world that Rina Banerjee creates through her installation work is dichotomous: impressive in its size yet simple in many of its materials; mysterious in its approach yet forthright in its message. And the almost effortless and tranquil appearance of, say, a floating pink Taj Mahal, directly contrasts the detailed and demanding work that went ...",
    url: "/works/installing-take-me-to-the-palace-of-love-ac",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 3,
    category: "essays",
    author_name: "Julia Neufeld",
    title: "Behind the Scenes: Installing “Take Me to the Palace of Love”",
    cover_img: "/images/portal/behind_scenes_jn.jpg",
    desc: "Installing Rina Banerjee’s monumental works for <i>Take Me to the Palace of Love</i> was an experience unlike any I’ve had in a museum. Unlike the prints, paintings, and smaller sculptures included in the exhibition, Rina’s enormous installations were physically demanding. Her unconventional materials—the metal frameworks of all the sculptures, the ...",
    url: "/works/installing-take-me-to-the-palace-of-love-jn",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 4,
    category: "essays",
    author_name: "Rebecca M. Brown",
    title: "Infectious Transmissions: Rina Banerjee in Two Dimensions",
    cover_img: "/images/portal/infectious_transmissions_rb.jpg",
    desc: "Rina Banerjee’s sculpture–installations interrupt the gallery space, as she uses myriad media to create effusive, organic, overwhelming constructions that engage our senses. We are drawn to these detailed compilations of forms, and we are alert: they ask us to come close but they also seem to reach out towards us with a hint of threat. They are infectious, in all senses of the word ...",
    url: "/works/infectious-transmissions",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 5,
    category: "essays",
    author_name: "Natalie Rieth",
    title: "Love in Syracuse: Making Art Together",
    cover_img: "/images/portal/love_syracuse_nr.jpg",
    desc: "Relationship building is innate to art, whether it be a common understanding between an artist's work and its spectator’s lived experience, or the connections formed by creators who make art together. <br />“You need a community to have value connected to art,” artist and sculptor Rina Banerjee said. “People decide whether they are attracted to an ...",
    url: "/works/love-in-syracuse-making-art-together",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 6,
    category: "essays",
    author_name:"Jason Vartikar",
    title: "Mermaid Thoughts",
    cover_img: "/images/portal/mermaid_thoughts_jv.jpg",
    desc: "Are there real magical objects anymore? Medieval crowns and crystal ewers were once meant to carry divine power. Today, scholars shy from the idea that objects are literally magical. Here, I explore if Rina Banerjee’s 2017 sculpture <i>Viola…</i> may have such power. I explore how the sculpture may compare to the legendary, magical songs of sirens   ...",
    url: "/works/mermaid-thoughts",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 7,
    category: "essays",
    author_name: "Timur Hammond",
    title: "Other Routes of the Image: Looking at Rina Banerjee by Way of Istanbul",
    cover_img: "/images/portal/other_routes_th.jpg",
    desc: "Introducing his research into the ‘image’ of American cities in the 1950s, Kevin Lynch wrote, “Looking at cities can give a special pleasure… At every instant, there is more than the eye can see, more than the ear can hear, a setting or a view waiting to be explored. Nothing is experienced by itself, but always in relation to its surroundings, the ...",
    url: "/works/other-routes-of-the-image",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 8,
    category: "essays",
    author_name: "Kate Holohan",
    title: "Reflection: “Take Me to the Palace of Love”",
    cover_img: "/images/portal/reflection_kh.jpg",
    desc: "I sometimes analogize museum work to the movement of a duck in water. To museum visitors, exhibitions and programs often appear polished and carefully executed, as graceful as a duck gliding across a pond. Yet underneath this surface, the paddling feet of curators, educators, registrars, preparators, administrators, and ...",
    url: "/works/reflection-take-me-to-the-palace-of-love",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 9,
    category: "essays",
    author_name: "Mike Goode",
    title: "Scale Modeling: The Climate of Rina Banerjee’s “A World Lost…”",
    cover_img: "/images/portal/scale_modeling_mg.jpg",
    desc: "Rina Banerjee’s <i>A World Lost…</i>(2013) dangles an inverted dome-shaped, plastic horn-adorned, incandescent lightbulb-bedazzled, metal frame precariously over a colorful assemblage that combines organic and inorganic materials sourced from around the world (fig. 1). Comprised of sand, shells, plant forms woven from textiles, feathers, pebbles ...",
    url: "/works/scale-modeling",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 10,
    category: "essays",
    author_name: "Lawrence Chua",
    title: "Stranger in the Palace of Love",
    cover_img: "/images/portal/stranger_palace_lc.jpg",
    desc: "Both cenotaph and tomb, the Taj Mahal operates as both a monument to love and a monument to death. But its history as a romantic site is of more recent provenance than its history as a monument to temporality. Its formalist geometry and symmetry as well as its gleaming marble cladding create a stunning visual effect, the contradictory appearance ...",
    url: "/works/stanger-in-the-palace-of-love",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 11,
    category: "essays",
    author_name: "Melissa Yuen",
    title: "“Take me, take me, take me... to the art museum”",
    cover_img: "/images/portal/take_me_art_museum_my.jpg",
    desc: "On view during the Spring 2023 semester, <i>Take Me to the Palace of Love</i> showcased the importance of art and highlighted the central role a university art museum plays on a college campus (fig. 1). Featuring sculptures and drawings made by Rina Banerjee, the installation was visually compelling and conceptually rich, with the large sculptures and ...",
    url: "/works/take-me-art-museum",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 12,
    category: "essays",
    author_name: "Danielle Taana Smith",
    title: "“Take Me to the Palace of Love”: Teaching Out Loud about the Arts, Resistance and the Curriculum of Love",
    cover_img: "/images/portal/teaching_out_ds.jpg",
    desc: "Despite serious contestations and attempts to establish new poles of power, palaces in Washington, London, Brussels, Paris, and other Western cities are understood as imperial seats, representing the core of the global empire from whence economo-political power reigns. However, Foucault reminds us that “power is everywhere,” even though the ...",
    url: "/works/teaching-arts-resistance-curriculum-of-love",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 13,
    category: "essays",
    author_name: "Joan Bryant",
    title: "“Tell Me Whom You Love”: ‘Mixed’ Marriage & Racial Mutability",
    cover_img: "/images/portal/tell_me_jb.jpg",
    desc: "Indian peddlers and seamen who migrated to the United States during the 1890s and the early decades of the twentieth century frame Rina Banerjee’s <i>Viola, from New Orleans</i> (2017) (fig.1). The Bengali men who initially made this journey established themselves by supplying American consumers with “Oriental” wares - silks, curios, perfumes, and rugs ...",
    url: "/works/tell-me-whom-you-love",
    time: "",
    date: "",
    icon: <SiGoogledocs className="text-white text-4xl" />
  },
  {
    id: 14,
    category: "poems",
    author_name: "Justo Triana",
    title: "To the Palace of Love",
    cover_img: "/images/poems/poem_justo.jpg",
    desc: "Take me <br /> to the Palace of Love <br /> before the Taj...",
    url: "/works/to-the-palace-of-love",
    time: "",
    date: "",
    icon: <FaFeatherPointed className="text-white text-4xl" />
  },
  {
    id: 15,
    category: "poems",
    author_name: "Zamzam Mohamed",
    title: "Unearthing my Identity through Viola",
    cover_img: "/images/poems/poem_zamzam.jpg",
    desc: "As I wander through these halls, <br /> my eyes alight on a figure that calls...",
    url: "/works/unearthing-my-identity-through-viola",
    time: "",
    date: "",
    icon: <FaFeatherPointed className="text-white text-4xl" />
  },
  {
    id: 16,
    category: "poems",
    author_name: "Khadija Sharif",
    title: "Viola's Love Story",
    cover_img: "/images/poems/poem1_khadija.jpg",
    desc: "That’s why I wear the mask <br /> As I uttered the prayer <br /> Ewat Ewat Ewat meel Jacel egay...",
    url: "/works/violas-love-story",
    time: "",
    date: "",
    icon: <FaFeatherPointed className="text-white text-4xl" />
  },
  {
    id: 17,
    category: "poems",
    author_name: "Khadija Sharif",
    title: "A World Lost",
    cover_img: "/images/poems/poem2_khadija.jpg",
    desc: "It is important you know What calms the waterfall’s anger <br /> Currents so wild...",
    url: "/works/a-world-lost",
    time: "",
    date: "",
    icon: <FaFeatherPointed className="text-white text-4xl" />
  },
  {
    id: 18,
    category: "lectures",
    author_name: "Ankush Arora",
    title: "Being Rina Banerjee: In conversation with Ankush Arora, Natalie Rieth, and Sam Johnson",
    cover_img: "/images/videos/being_rina_banerjee_18.jpg",
    desc: "Graduate students Ankush Arora (Art History) and Natalie Rieth (Goldring Arts Journalism & Communications) introduce Rina Banerjee in a conversation moderated by Professor Sam Johnson (Art History). Department of Art & Music Histories, Syracuse University. For <i>Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/being-rina-banerjee",
    youtube: "https://www.youtube.com/embed/7U1n4x-OHYM",
    time: "1:04:04",
    date: "February 20, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/black-noodles-replenishing-reaping-the-earth",
    next: "/lectures/matters-out-of-place"
  },
  {
    id: 19,
    category: "lectures",
    author_name: "",
    title: "Matters Out of Place",
    cover_img: "/images/videos/matters_out_of_place_19.jpg",
    desc: "Timur Hammond (Geography) and Lawrence Chua (Architecture) join artist Rina Banerjee to discuss materiality, time, architecture, and geography in Banerjee’s \"Take Me, Take Me...to the Palace of Love\" (2003) and \"A World Lost\" (2013). For <i>Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/matters-out-of-place",
    youtube: "https://www.youtube.com/embed/IGsToj_CJy8",
    time: "1:04:50",
    date: "February 21, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/being-rina-banerjee",
    next: "/lectures/tell-me-who-you-love-race-and-kinship"
  },
  {
    id: 20,
    category: "lectures",
    author_name: "",
    title: "Tell Me Who You Love? Race and Kinship",
    cover_img: "/images/videos/race_and_kinship_20.jpg",
    desc: "Joan Bryant (African American Studies) and Romita Ray (Art History) talk with Rina Banerjee about inter-racial marriage, diaspora, and identity in response to Banerjee’s \"Viola, from New Orleans-\" (2017) and objects from the collections of the Syracuse University Art Museum. <i>For Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/tell-me-who-you-love-race-and-kinship",
    youtube: "https://www.youtube.com/embed/OJ2YJ_fumt0",
    time: "1:10:25",
    date: "February 22, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/matters-out-of-place",
    next: "/lectures/knowing-through-looking"
  },
  {
    id: 21,
    category: "lectures",
    author_name: "",
    title: "Knowing Through Looking",
    cover_img: "/images/videos/knowing_through_looking_21.jpg",
    desc: "Focusing on Rina Banerjee’s drawings, Art History graduate student Ankush Arora ('23) talks with Banerjee about her drawings and curating an exhibition of Mithila art from India. For <i>Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/knowing-through-looking",
    youtube: "https://www.youtube.com/embed/GvZ7R1MgUis",
    time: "59:05",
    date: "March 1, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/tell-me-who-you-love-race-and-kinship",
    next: "/lectures/a-world-lost-climate-change-art-and-law"
  },
  {
    id: 22,
    category: "lectures",
    author_name: "",
    title: "A World Lost? Climate Change, Art, and Law",
    cover_img: "/images/videos/world_lost_climate_art_law_22.jpg",
    desc: "David M. Driesen, University Professor (Law) and Mike Goode, William P. Tolley Distinguished Teaching Professor in the Humanities (English) engage Rina Banerjee in critical conversation about climate change, art, and law. For <i>Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/a-world-lost-climate-change-art-and-law",
    youtube: "https://www.youtube.com/embed/rVc4kTICdm0",
    time: "1:16:11",
    date: "March 2, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/knowing-through-looking",
    next: "/lectures/in-conversation-with-gayatri-spivak"
  },
  {
    id: 23,
    category: "lectures",
    author_name: "",
    title: "In Conversation with Gayatri Spivak",
    cover_img: "/images/videos/conversation_gayatri_spivak_23.jpg",
    desc: "Rina Banerjee and internationally renowned scholar, Gayatri Spivak discuss reason and imagination, and sign and trace. The conversation marked the finale of Banerjee's residency as Jeannette K. Watson Distinguished Visiting Professor in the Humanities at Syracuse University. Joyce Hergenhan Auditorium, Newhouse School, Syracuse University. For <i>Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/in-conversation-with-gayatri-spivak",
    youtube: "https://www.youtube.com/embed/u9LPht6Jshs",
    time: "1:33:24",
    date: "March 3, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/a-world-lost-climate-change-art-and-law",
    next: "/lectures/lunchtime-lecture-mithila-paintings"
  },
  {
    id: 24,
    category: "lectures",
    author_name: "",
    title: "Lunchtime Lecture: Mithila Paintings",
    cover_img: "/images/videos/mithila_paintings_24.jpg",
    desc: "Susan Wadley (Professor Emeritus, Anthropology) discusses Mithila paintings in the collection of the Syracuse University Art Museum on April 5, 2023. Curated by Ankush Arora (MA.,'23) in the Department of Art and Music Histories at Syracuse University, with guidance from professor Wadley, the Mithila art wall was organized in response to Rina Banerjee's drawings in <i>Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/lunchtime-lecture-mithila-paintings",
    youtube: "https://www.youtube.com/embed//wlHZWFg0dfE",
    time: "37:55",
    date: "April 5, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/in-conversation-with-gayatri-spivak",
    next: "/lectures/a-chant-performance-with-amarachi-attamah"
  },
  {
    id: 25,
    category: "lectures",
    author_name: "",
    title: "A Chant Performance with Amarachi Attamah",
    cover_img: "/images/videos/chant_performance_amarachi_25.jpg",
    desc: "A Chant Performance with Amarachi Attamah (Museum Studies, G’23), in response to Rina Banerjee's \"Viola, from New Orleans-\" (2017). Introduced by Ruth Opara (Art and Music Histories), 2022-23 Art Museum Faculty Fellow. For <i>Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/a-chant-performance-with-amarachi-attamah",
    youtube: "https://www.youtube.com/embed/yLI0Dc3trTk",
    time: "36:04",
    date: "April 12, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/lunchtime-lecture-mithila-paintings",
    next: "/lectures/narratio-fellows-poetry-performance"
  },
  {
    id: 26,
    category: "lectures",
    author_name: "",
    title: "Narratio Fellows Poetry Performance",
    cover_img: "/images/videos/narratio_fellows_26.jpg",
    desc: "Narratio Fellows Khadija Sharif, Zamzam Mohamed, and Justo Antonio Triana read original poetry inspired by Rina Banerjee’s \"Take Me to the Palace of Love\" exhibition, along with a short film screening by Narratio Fellow alum Rayan Mohamed. Introduced by Brice Nordquist, Dean’s Professor of Community Engagement, Syracuse University. Co-sponsored by the <a href=\"https://artsandsciences.syracuse.edu/engaged-humanities/\" target=\"_blank\">Engaged Humanities Network</a> and the National Endowment for the Arts. For <i>Take Me to the Palace of Love</i>, Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/narratio-fellows-poetry-performance",
    youtube: "https://www.youtube.com/embed/QTppFa3XbRc",
    time: "49:52",
    date: "April 20, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/a-chant-performance-with-amarachi-attamah",
    next: "/lectures/black-noodles-replenishing-reaping-the-earth"
  },
  {
    id: 27,
    category: "lectures",
    author_name: "",
    title: "Black Noodles, Replenishing/Reaping the Earth",
    cover_img: "/images/videos/black_noodles_27.jpg",
    desc: "“Between birth and death the constant spins and oodles of noodles migrate, waffle uncertainty.” Banerjee takes to the podium at Syracuse University to explore diaspora, displacement, and science in her drawings and art installations in the exhibition, Take Me to the Palace of Love at the Syracuse University Art Museum (January 19 – May 14, 2023).",
    url: "/lectures/black-noodles-replenishing-reaping-the-earth",
    youtube: "https://www.youtube.com/embed/YwdR2DITHhU",
    time: "1:15:53",
    date: "February 23, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/narratio-fellows-poetry-performance",
    next: "/lectures/making_art_with_rina_banerjee"
  },
  {
    id: 28,
    category: "lectures",
    author_name: "Rayan Mohamed",
    title: "“Love in Syracuse”: Making art with Rina Banerjee, filmed by Rayan Mohamed",
    cover_img: "/images/videos/love_syr_making_art_28.jpg",
    desc: "Syracuse University students, staff, and faculty join Rina Banerjee, members of the Syracuse community, and Narratio Fellows to make art together in the community room at Salt City Market in Downtown Syracuse. Filmed by Rayan Mohamed, Narratio Fellow Alum. “Take Me to the Palace of Love,” Syracuse University Art Museum (January 19 – May 14,  2023).",
    url: "/lectures/making_art_with_rina_banerjee",
    youtube: "https://www.youtube.com/embed/quWniMf-hzc",
    time: "08:09",
    date: "February 25, 2023",
    icon: <FaVideo className="text-white text-4xl" />,
    prev: "/lectures/narratio-fellows-poetry-performance",
    next: "/lectures/being-rina-banerjee"
  },
];

export default data;